Adds support for the Bitski browser extension wallet
wagmi-dev/references pull request #116
Opened 2023-02-16 22:36 UTC by pzuraq

## Description

Add support for Bitski's new browser extension wallet

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address: 0xb9b7d3d6317d987548919641c8bf1f539da275fc

2023-02-16 22:56 UTC, pzuraq commented
I don't believe the test failure was related to this change but I could be wrong, let me know if I am

2023-02-17 00:56 UTC, tmm commented on .changeset/purple-ligers-jog.md
> +Add support for Bitski injected wallet
```suggestion
Added name mapping for Bitski
```

2023-02-17 00:56 UTC, tmm commented on .changeset/purple-ligers-jog.md
> +'@wagmi/connectors': minor
```suggestion
'@wagmi/connectors': patch
```

2023-02-17 00:57 UTC, tmm requested changes
Looking good. Please update the test `getInjectedName.test.ts` for `isBitski`.

2023-02-17 01:01 UTC, pzuraq commented
@tmm updated!

2023-02-17 01:48 UTC, merged