Support polygon zkevm testnet
wagmi-dev/references pull request #119
Opened 2023-02-17 03:31 UTC by graykode

## Description

Support polygon zkevm testnet : https://public.zkevm-test.net/  
[@tmm](https://github.com/tmm)

## Additional Information

- [ ] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address:
`0x5F79EE8f8fA862E98201120d83c4eC39D9468D49`

2023-02-17 07:43 UTC, graykode commented
I think `VITE_WC_PROJECT_ID` ci is not work... Can you see this when review?

2023-02-19 22:15 UTC, tmm requested changes
Please add a [changeset](https://github.com/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md#versioning)

2023-02-21 21:32 UTC, graykode commented
@tmm Sure! I've added: https://github.com/wagmi-dev/references/pull/119/commits/f38d62afeaeecd915cd8b3dc6b60efa8b21bda69

2023-02-21 21:56 UTC, tmm approved these changes

2023-02-21 21:58 UTC, merged