Adding Klaytn, Dogechain, DFK, and Cronos
wagmi-dev/references pull request #149
Opened 2023-03-09 01:29 UTC by simonmahns

## Description

Added Klaytn, Dogechain, DFK, and Cronos, ammended an error in the boba file.

2023-03-09 21:18 UTC, tmm requested changes
Please add a patch [changeset](https://github.com/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md#versioning)

2023-03-09 21:18 UTC, tmm commented on packages/chains/src/cronos.ts
> +      default: { name: 'CronosScan', url: 'https://cronoscan.com/' },
```suggestion
      etherscan: { name: 'CronosScan', url: 'https://cronoscan.com' },
      default: { name: 'CronosScan', url: 'https://cronoscan.com' },
```

2023-03-09 21:18 UTC, tmm commented on packages/chains/src/dfk.ts
> +    id: 53935,
```suggestion
    id: 53_935,
```

2023-03-09 21:18 UTC, tmm commented on packages/chains/src/dfk.ts
> +      public: { http: ['https://subnets.avax.network/defi-kingdoms/dfk-chain/rpc	'] },
```suggestion
      default: { http: ['https://subnets.avax.network/defi-kingdoms/dfk-chain/rpc'] },
      public: { http: ['https://subnets.avax.network/defi-kingdoms/dfk-chain/rpc'] },
```

2023-03-09 21:18 UTC, tmm commented on packages/chains/src/dogechain.ts
> +    id: 2000,
```suggestion
    id: 2_000,
```

2023-03-09 21:18 UTC, tmm commented on packages/chains/src/dogechain.ts
> +      default: { http: ['https://rpc.dogechain.dog	'] },
```suggestion
      default: { http: ['https://rpc.dogechain.dog'] },
```

2023-03-09 21:18 UTC, tmm commented on packages/chains/src/klaytn.ts
> +      public: { http: ['https://cypress.fautor.app/archive	'] },
```suggestion
      default: { http: ['https://cypress.fautor.app/archive'] },
      public: { http: ['https://cypress.fautor.app/archive'] },
```

2023-03-09 21:18 UTC, tmm commented on packages/chains/src/klaytn.ts
> +    id: 8217,
```suggestion
    id: 8_217,
```

2023-03-09 21:18 UTC, tmm commented on packages/chains/src/klaytn.ts
> +      default: { name: 'KlaytnScope', url: 'https://scope.klaytn.com/' },
```suggestion
      etherscan: { name: 'KlaytnScope', url: 'https://scope.klaytn.com' },
      default: { name: 'KlaytnScope', url: 'https://scope.klaytn.com' },
```

2023-03-09 23:27 UTC, simonmahns commented
> Please add a patch [changeset](https://github.com/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md#versioning)

Hey, added change set (first time using, cool software!) and fixed changes. Thanks for the feedback.

2023-03-10 01:41 UTC, tmm requested changes
Please make sure all these chains are exported from the `index.ts` file

2023-03-10 01:49 UTC, merged