shibuya added
wagmi-dev/references pull request #158
Opened 2023-03-13 15:48 UTC by msantamaria86

## Description
Added shibuya, a testnet for the Astar network on Polkadot (evm compatible)

## Additional Information
- [ X] I read the contributing docs

Your ENS/address:
0x0C5981f7091aa22C57C5871F5540e136a63bfF1D

2023-03-13 17:56 UTC, tmm requested changes
Please add a patch [changeset](https://github.com/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md#versioning) and export the chain from the `index.ts` file

2023-03-13 17:56 UTC, tmm commented on packages/chains/src/shibuya.ts
> +      url: 'https://shibuya.subscan.io/',
```suggestion
      url: 'https://shibuya.subscan.io',
```

2023-03-13 17:56 UTC, tmm commented on packages/chains/src/shibuya.ts
> +    public: { http: ['https://evm.shibuya.astar.network/'] },
```suggestion
    default: { http: ['https://evm.shibuya.astar.network'] },
    public: { http: ['https://evm.shibuya.astar.network'] },
```

2023-03-13 17:56 UTC, tmm commented on packages/chains/src/shibuya.ts
> +}
```suggestion
export const shibuya = {
  id: 81,
  name: 'Shibuya Network',
  network: 'Shibuya-network',
  nativeCurrency: {
    decimals: 18,
    name: 'shibuya',
    symbol: 'SBY',
  },
  rpcUrls: {
    default: { http: ['https://evm.shibuya.astar.network/'] },
    public: { http: ['https://evm.shibuya.astar.network/'] },
  },
  blockExplorers: {
    default: {
      name: 'Shibuya Explorer',
      url: 'https://shibuya.subscan.io/',
    },
  },
  testnet: true,
} as const satisfies Chain
```

2023-03-13 20:43 UTC, msantamaria86 commented
changeset created

2023-03-13 22:39 UTC, msantamaria86 commented
changes addressed

2023-03-14 17:54 UTC, tmm requested changes

2023-03-14 17:54 UTC, tmm commented on .changeset/fluffy-flowers-hear.md
> +'@wagmi/chains': minor
```suggestion
'@wagmi/chains': patch
```

2023-03-14 17:54 UTC, tmm commented on .changeset/real-hairs-exercise.md
> +Added ASTAR's shibuya testnet
Please remove this changeset

2023-03-14 17:54 UTC, tmm commented on packages/connectors/src/index.ts
> +export const shibuya = {
Please remove this change. `shibuya` should be exported from `packages/chains/src/index.ts`

2023-03-14 17:54 UTC, tmm commented on packages/chains/src/shibuya.ts
> +}
```suggestion
import { Chain } from './types'

export const shibuya = {
  id: 81,
  name: 'Shibuya Network',
  network: 'Shibuya-network',
  nativeCurrency: {
    decimals: 18,
    name: 'shibuya',
    symbol: 'SBY',
  },
  rpcUrls: {
    default: { http: ['https://evm.shibuya.astar.network/'] },
    public: { http: ['https://evm.shibuya.astar.network/'] },
  },
  blockExplorers: {
    default: {
      name: 'Shibuya Explorer',
      url: 'https://shibuya.subscan.io',
    },
  },
  testnet: true,
} as const satisfies Chain
```

2023-03-16 23:14 UTC, closed without merging

2023-03-16 23:16 UTC, jxom commented
Didn't mean to close. PR at #172 (commits preserved)