Add isDawn flag to `InjectedProviderFlags`
wagmi-dev/references pull request #173
Opened 2023-03-17 01:43 UTC by thomas-waite

## Description
Dawn Wallet is an iOS based Ethereum wallet with a native Safari extension: https://twitter.com/dawn_wallet. We are integrating into ConnectKit - ConnectKit uses the `Ethereum` type from wagmi, which itself uses the `InjectedProviderFlags` to recognise injected wallets. 

We need the `isDawn` flag to be available on the type in ConnectKit (see this PR: https://github.com/family/connectkit/pull/162). This PR in wagmi adds it.

Your ENS/address: tomwaite.eth

2023-03-17 02:06 UTC, jxom requested changes
Thanks for the PR!

Can you please add a patch `changeset` via `pnpm changeset`?

Will also need to add Dawn into [`getName`](https://github.com/wagmi-dev/references/blob/04106f41506fd7b856d638a13f1a710098b3b426/packages/connectors/src/utils/getInjectedName.ts#L6) and the [tests](https://github.com/wagmi-dev/references/blob/04106f41506fd7b856d638a13f1a710098b3b426/packages/connectors/src/utils/getInjectedName.test.ts#L6).

2023-03-17 02:52 UTC, thomas-waite commented
> Thanks for the PR!
> 
> Can you please add a patch `changeset` via `pnpm changeset`?
> 
> Will also need to add Dawn into [`getName`](https://github.com/wagmi-dev/references/blob/04106f41506fd7b856d638a13f1a710098b3b426/packages/connectors/src/utils/getInjectedName.ts#L6) and the [tests](https://github.com/wagmi-dev/references/blob/04106f41506fd7b856d638a13f1a710098b3b426/packages/connectors/src/utils/getInjectedName.test.ts#L6).

Done! Let me know if anything else needs doing

2023-03-17 18:34 UTC, thomas-waite commented
@jxom Lmk when this looks good to go, need to get this merged and a new package published for our connector PR in ConnectKit: https://github.com/family/connectkit/pull/162 

Thanks for reviewing!

2023-03-18 17:39 UTC, tmm approved these changes

2023-03-18 17:39 UTC, tmm commented on .changeset/ninety-needles-greet.md
> +Add isDawn wallet flag
```suggestion
Added Dawn wallet flag
```

2023-03-19 04:52 UTC, merged