Add Neon EVM Devnet Support
wagmi-dev/references pull request #206
Opened 2023-03-30 14:43 UTC by Sj-001

## Description

Added neonDevnet.ts in references/packages/chains/src
Added import for neonDevnet.ts in references/packages/chains/src/index.ts

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address: 0xDf2AC80661DAB9010f9B9cc88e43f3d2E1035fF4

2023-03-30 15:02 UTC, codingwithmanny commented on packages/chains/src/neonDevnet.ts
> +
@Sj-001 might be a linting issue. I recommend running the lints within package.json

2023-03-30 15:08 UTC, Sj-001 commented on packages/chains/src/neonDevnet.ts
> +
@codingwithmanny i am getting a bunch of errors 
![image](https://user-images.githubusercontent.com/50135847/228881041-9a070902-4015-4e60-abec-bd37d3611845.png)

2023-03-30 17:16 UTC, codingwithmanny commented on packages/chains/src/neonDevnet.ts
> +
I'd recommend using pnpm instead of yarn or npm in this case. 
There are somethings setup with the repository that just work better with pnpm in this case.

Not sure if that will solve things, but make sure to delete all your node modules and any yarn.lock files before doing a pnpm install.

2023-04-03 18:13 UTC, tmm requested changes

2023-04-03 18:13 UTC, tmm commented on .changeset/giant-zoos-think.md
> +'@wagmi/chains': minor
```suggestion
'@wagmi/chains': patch
```

2023-04-03 18:13 UTC, tmm commented on .changeset/giant-zoos-think.md
> +Added neonDevnet.ts in references/packages/chains/srcAdded import for neonDevnet.ts in references/packages/chains/src/index.ts
```suggestion
Added Neon Devnet.
```

2023-04-03 18:13 UTC, tmm commented on .gitignore
let's not change this file. please revert changes to it.

2023-04-03 18:13 UTC, tmm commented on packages/chains/src/neonDevnet.ts
> +  id: 245022926,
```suggestion
  id: 245_022_926,
```

2023-04-03 18:13 UTC, tmm commented on packages/chains/src/neonDevnet.ts
> +      url: 'https://neonscan.org/',
```suggestion
      url: 'https://neonscan.org',
```

2023-04-03 18:13 UTC, tmm commented on pnpm-lock.yaml
please revert changes to the lock file

2023-04-04 08:10 UTC, Sj-001 commented
Hey @tmm , thank you for your suggestions. Please merge the changes:)

2023-04-04 23:25 UTC, tmm requested changes
Ready to go once you revert changes to two files.

2023-04-04 23:25 UTC, tmm commented on .gitignore
Please revert this change

2023-04-04 23:25 UTC, tmm commented on pnpm-lock.yaml
Please revert this change

2023-04-05 08:37 UTC, closed without merging