Add Conflux eSpace
wagmi-dev/references pull request #210
Opened 2023-04-03 10:29 UTC by darwintree

## Description

Add Conflux eSpace

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address:

2023-04-03 18:11 UTC, tmm requested changes
Looking good. The [multicall3 contract](https://evm.confluxscan.io/address/0xeff0078910f638cd81996cc117bccd3edf2b072f?tab=contract-viewer) isn't verified though. Any chance you can verify or deploy another that is?

2023-04-04 01:44 UTC, darwintree commented
> Looking good. The [multicall3 contract](https://evm.confluxscan.io/address/0xeff0078910f638cd81996cc117bccd3edf2b072f?tab=contract-viewer) isn't verified though. Any chance you can verify or deploy another that is?

Sorry for that. 
Previous verified at another domain(https://evm.confluxscan.net/address/0xeff0078910f638cd81996cc117bccd3edf2b072f) but the verification data is somehow not shared. 
Now both are verified(https://evm.confluxscan.io/address/0xeff0078910f638cd81996cc117bccd3edf2b072f?tab=contract-viewer)
BTW: the 2 scan provided at different domain is generally exactly the same but with different server location(`.net` at Hong Kong and `.io` at US East) and it is the same for public RPCs(https://doc.confluxnetwork.org/docs/espace/build/network-endpoints). Although current configuration is generally ok, but I wonder that if I want to add `.net`  ones, what is the recommended way to label these 2 domains?

2023-04-04 02:03 UTC, tmm commented on packages/chains/src/cfxESpace.ts
> +export const cfxESpace = {
Should we call this `confluxESpace` instead? Bit more verbose, but is more easily searchable and autocomplete-able.

2023-04-04 02:11 UTC, darwintree commented on packages/chains/src/cfxESpace.ts
> +export const cfxESpace = {
Renamed

2023-04-04 23:25 UTC, tmm approved these changes

2023-04-04 23:25 UTC, merged