Adds pulsechain networks
wagmi-dev/references pull request #258
Opened 2023-04-24 17:58 UTC by 3commascapital

## Description

adds pulsechain networks (testnet + mainnet)

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

2023-04-25 22:47 UTC, tmm requested changes
Please add a patch changeset with `pnpm changeset`

2023-04-25 22:47 UTC, tmm commented on packages/chains/src/pulsechainV4.ts
> +    },
```suggestion
```

2023-04-25 22:47 UTC, tmm commented on packages/chains/src/pulsechainV4.ts
> +      address: '0xca11bde05977b3631167028862be2a173976ca11',
Looks like this contract is [not verified](https://scan.v4.testnet.pulsechain.com/address/0xcA11bde05977b3631167028862bE2a173976CA11). Please verify it or a deploy a new verified version.

2023-04-25 22:47 UTC, tmm commented on packages/chains/src/pulsechainV4.ts
> +    },
Not an official ENS deployment AFAIK

```suggestion
```

2023-04-25 22:47 UTC, tmm commented on packages/chains/src/pulsechain.ts
> +    },
```suggestion
```

2023-04-25 22:47 UTC, tmm commented on packages/chains/src/pulsechain.ts
> +    },
This link 404'd. Have another that works?

2023-04-25 22:47 UTC, tmm commented on packages/chains/src/pulsechain.ts
> +    },
Not an official ENS deployment AFAIK

```suggestion
```

2023-04-26 14:36 UTC, 3commascapital commented on packages/chains/src/pulsechainV4.ts
> +    },
this address is the same because the system state of ethereum is coming along for the ride. ens's private keys and exact state at the fork block will be preserved

2023-04-26 14:38 UTC, 3commascapital commented on packages/chains/src/pulsechainV4.ts
> +      address: '0xca11bde05977b3631167028862be2a173976ca11',
block explorer is not currently loading libs. comparing bytecode shows match

2023-05-04 17:14 UTC, tmm approved these changes

2023-05-04 17:14 UTC, tmm commented on .changeset/green-masks-leave.md
> +'@wagmi/connectors': patch
```suggestion
```

2023-05-04 17:14 UTC, merged