feat: add Enkrypt
wagmi-dev/references pull request #260
Opened 2023-04-25 21:35 UTC by kvhnuke

## Description

add Enkrypt injected wallet detection

2023-04-25 22:41 UTC, tmm requested changes
Please add a patch changeset (`pnpm changeset`) and add a test case for `getInjectedName.ts`

2023-04-26 01:04 UTC, kvhnuke commented
@tmm please let me know if you need any other changes

2023-04-26 01:23 UTC, tmm commented on .changeset/seven-bottles-film.md
> +Add Enkrypt extension detection
```suggestion
Added Enkrypt extension detection
```

2023-04-26 01:23 UTC, tmm commented on .changeset/seven-bottles-film.md
> +'@wagmi/connectors': minor
```suggestion
'@wagmi/connectors': patch
```

2023-04-26 03:52 UTC, tmm approved these changes

2023-04-26 03:52 UTC, merged