Update: Kucoin Wallet upgrade to Halo Wallet
wagmi-dev/references pull request #264
Opened 2023-04-27 11:30 UTC by Louis-kupo

## Description
  
As KuCoin Wallet rebranded to Halo Wallet, the keyword needs to be updated to isHaloWallet.

The official website of KuCoin Wallet is https://www.kuwallet.com/, which has been redirected to https://halo.social/ - the official website of Halo Wallet.

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address:

2023-05-04 17:12 UTC, tmm requested changes

2023-05-04 17:12 UTC, tmm commented on .changeset/ninety-impalas-rest.md
> +'@wagmi/connectors': major
Transient, doesn't effect runtime behavior so making a `patch`

```suggestion
'@wagmi/connectors': patch
```

2023-05-04 17:12 UTC, tmm commented on .changeset/ninety-impalas-rest.md
> +Update: Kucoin Wallet upgrade to Halo Wallet
```suggestion
Changed Kucoin Wallet name mapping to Halo Wallet
```

2023-05-04 17:12 UTC, tmm commented on packages/connectors/src/types.ts
> +  isHaloWallet?: true
Should we remove the `isKuCoinWallet` flag?

2023-05-08 07:39 UTC, Louis-kupo commented on packages/connectors/src/types.ts
> +  isHaloWallet?: true
Thanks, we hope can keep the `isKuCoinWallet` flag . 
And I updated the latest PR code

2023-05-08 12:10 UTC, tmm approved these changes

2023-05-08 12:10 UTC, merged