Added ekta chain and ekta chain testnet to imports
wagmi-dev/references pull request #274
Opened 2023-05-08 04:59 UTC by begmuhommet

## Description

_Concise description of proposed changes_

## Additional Information

- [ ] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address:

2023-05-10 00:52 UTC, begmuhommet commented on pnpm-lock.yaml
Changeset removed

2023-05-10 21:05 UTC, tmm commented on pnpm-lock.yaml
We want to keep `.changeset`. I meant to remove your changes to the `pnpm-lock.yaml`. Once you restore `.changeset`, will be good to go.

2023-05-11 01:44 UTC, begmuhommet commented on pnpm-lock.yaml
Done. Thanks

2023-05-11 02:49 UTC, tmm requested changes

2023-05-11 02:49 UTC, tmm commented on packages/chains/src/index.ts
> +export { ektaTestnet } from './ektaTestnet'
Missed this earlier. Let's keep this in alphabetical order.

2023-05-11 03:18 UTC, begmuhommet commented on packages/chains/src/index.ts
> +export { ektaTestnet } from './ektaTestnet'
Sure. Done

2023-05-11 12:34 UTC, tmm approved these changes

2023-05-11 12:35 UTC, merged