Adding Defi Oracle Meta mainnet 138
wagmi-dev/references pull request #287
Opened 2023-05-15 11:36 UTC by defi-oracle

## Description

_Concise description of proposed changes_

## Additional Information

- [ ] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)  **Complies with all the must-haves.**

Your ENS/address: defi-oracle.eth

2023-05-23 18:01 UTC, tmm requested changes
Please add a changeset (`pnpm changeset`) and export the chain from the `index.ts` file.

2023-05-23 18:01 UTC, tmm commented on packages/chains/src/defi-oracle-meta.ts
> +      url: 'https://public-0138.defi-oracle.io',
This URL doesn't resolve.

2023-06-02 00:47 UTC, jxom commented
Closing for now as the chain data is malformed (Block Explorer URL does not resolve).

Can you please re-open a separate PR with the requested changes and make sure data is correct and working?

2023-06-02 00:47 UTC, closed without merging

2023-06-02 03:53 UTC, defi-oracle commented
I do not see a chain/rpc issue

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: jxom ***@***.***>
Sent: Thursday, June 1, 2023 5:47:20 PM
To: wagmi-dev/references ***@***.***>
Cc: Pandora Walker ***@***.***>; Author ***@***.***>
Subject: Re: [wagmi-dev/references] Adding Defi Oracle Meta mainnet 138 (PR #287)


Closing for now as the chain data is malformed (Block Explorer URL does not resolve).

Can you please re-open a separate PR with the requested changes and make sure data is correct and working?

—
Reply to this email directly, view it on GitHub<https://github.com/wagmi-dev/references/pull/287#issuecomment-1572967213>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A33O7TIF3RR5KDLPPA3TIVDXJEZZRANCNFSM6AAAAAAYCB2JBU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>