Desig Wallet support
wagmi-dev/references pull request #425
Opened 2023-07-13 07:10 UTC by thiennv-qng

## Description

_Concise description of proposed changes_

## Additional Information

- [ ] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address:

2023-07-13 21:48 UTC, tmm requested changes

2023-07-13 21:48 UTC, tmm commented on packages/connectors/src/types.ts
> +  isDesig?: true
Alphabetize

2023-07-13 21:48 UTC, tmm commented on packages/connectors/src/utils/getInjectedName.ts
> +    if (provider.isDesig) return 'Desig Wallet'
Alphabetize and add test case.

2023-07-13 21:48 UTC, tmm commented on .changeset/shiny-files-applaud.md
> +Desig Wallet support
```suggestion
Added Desig Wallet name mapping.
```

2023-07-20 04:14 UTC, thiennv-qng commented on packages/connectors/src/types.ts
> +  isDesig?: true
plz help me take a look again. tks

2023-07-20 04:14 UTC, thiennv-qng commented on packages/connectors/src/utils/getInjectedName.ts
> +    if (provider.isDesig) return 'Desig Wallet'
plz help me take a look again. tks

2023-07-20 04:14 UTC, thiennv-qng commented on .changeset/shiny-files-applaud.md
> +Desig Wallet support
plz help me take a look again. tks

2023-07-24 11:04 UTC, jxom approved these changes

2023-07-24 11:05 UTC, merged