feat(chains): add crossbell chain
wagmi-dev/references pull request #57
Opened 2023-01-13 23:48 UTC by Songkeys

## Description

_Concise description of proposed changes_

This adds crossbell chain support.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/22665058/212438384-c1f77088-f57b-4b91-a8af-d8477ab41a87.png">

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address: songkeys.eth

2023-01-19 15:27 UTC, tmm requested changes
Please add a patch [changeset](https://github.com/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md#versioning), then looks good to go.

2023-01-19 15:27 UTC, tmm commented on packages/chains/src/crossbell.ts
> +      blockCreated: 23499787,
```suggestion
      blockCreated: 23_499_787,
```

2023-01-19 15:27 UTC, tmm commented on packages/chains/src/crossbell.ts
> +  id: 3737,
```suggestion
  id: 3_737,
```

2023-01-20 19:02 UTC, merged

2023-01-28 06:17 UTC, Songkeys commented
Sorry I missed the review. I was on vacation. Thank you for the merge!